<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="shushudelichendebijibendiannao.local" ignored="0" name="Store Base Sync Tests" tests="3" failures="2" timestamp="2025-03-04T13:41:42 CST" time="15.556" errors="0">
  <testcase name="testStoreBaseSync_InvalidField" time="5.085" classname="com.saas.qa.api.testcase.open.store.StoreBaseSyncTest">
    <failure type="java.lang.AssertionError" message="结果不符合预期 expected [渠道ID不存在] but found [delFlg不为null,storeInfoRequest={&amp;quot;address&amp;quot;:&amp;quot;北京市朝阳区测试地址&amp;quot;,&amp;quot;channelId&amp;quot;:999,&amp;quot;longLat&amp;quot;:{&amp;quot;latitude&amp;quot;:999.999999,&amp;quot;longitude&amp;quot;:999.999999},&amp;quot;merchantId&amp;quot;:57,&amp;quot;posHub&amp;quot;:9,&amp;quot;saasStoreId&amp;quot;:7315,&amp;quot;selfServiceDistance&amp;quot;:1,&amp;quot;storeId&amp;quot;:&amp;quot;test57_hello&amp;quot;,&amp;quot;storeName&amp;quot;:&amp;quot;测试门店&amp;quot;,&amp;quot;storePosType&amp;quot;:9,&amp;quot;storeStatus&amp;quot;:9,&amp;quot;storeType&amp;quot;:9}]">
      <![CDATA[java.lang.AssertionError: 结果不符合预期 expected [渠道ID不存在] but found [delFlg不为null,storeInfoRequest={"address":"北京市朝阳区测试地址","channelId":999,"longLat":{"latitude":999.999999,"longitude":999.999999},"merchantId":57,"posHub":9,"saasStoreId":7315,"selfServiceDistance":1,"storeId":"test57_hello","storeName":"测试门店","storePosType":9,"storeStatus":9,"storeType":9}]
at com.saas.qa.api.testcase.open.store.StoreBaseSyncTest.testStoreBaseSync_InvalidField(StoreBaseSyncTest.java:91)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at com.saas.qa.api.util.TestReportGenerator.runTests(TestReportGenerator.java:73)
at com.saas.qa.api.util.TestReportGenerator.generateAndOpenReport(TestReportGenerator.java:53)
at com.saas.qa.api.util.TestReportGenerator.main(TestReportGenerator.java:154)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testStoreBaseSync_InvalidField -->
  <testcase name="testStoreBaseSync_MissingRequired" time="5.096" classname="com.saas.qa.api.testcase.open.store.StoreBaseSyncTest">
    <failure type="java.lang.AssertionError" message="结果不符合预期 expected [门店名称不能为空] but found [delFlg不为null,storeInfoRequest={&amp;quot;address&amp;quot;:&amp;quot;北京市朝阳区测试地址&amp;quot;,&amp;quot;channelId&amp;quot;:2,&amp;quot;longLat&amp;quot;:{&amp;quot;latitude&amp;quot;:39.909946,&amp;quot;longitude&amp;quot;:116.397428},&amp;quot;merchantId&amp;quot;:57,&amp;quot;posHub&amp;quot;:0,&amp;quot;saasStoreId&amp;quot;:7315,&amp;quot;selfServiceDistance&amp;quot;:1,&amp;quot;storeId&amp;quot;:&amp;quot;test57_hello&amp;quot;,&amp;quot;storePosType&amp;quot;:1,&amp;quot;storeStatus&amp;quot;:1,&amp;quot;storeType&amp;quot;:0}]">
      <![CDATA[java.lang.AssertionError: 结果不符合预期 expected [门店名称不能为空] but found [delFlg不为null,storeInfoRequest={"address":"北京市朝阳区测试地址","channelId":2,"longLat":{"latitude":39.909946,"longitude":116.397428},"merchantId":57,"posHub":0,"saasStoreId":7315,"selfServiceDistance":1,"storeId":"test57_hello","storePosType":1,"storeStatus":1,"storeType":0}]
at com.saas.qa.api.testcase.open.store.StoreBaseSyncTest.testStoreBaseSync_MissingRequired(StoreBaseSyncTest.java:68)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at com.saas.qa.api.util.TestReportGenerator.runTests(TestReportGenerator.java:73)
at com.saas.qa.api.util.TestReportGenerator.generateAndOpenReport(TestReportGenerator.java:53)
at com.saas.qa.api.util.TestReportGenerator.main(TestReportGenerator.java:154)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testStoreBaseSync_MissingRequired -->
  <testcase name="testStoreBaseSync_Success" time="5.368" classname="com.saas.qa.api.testcase.open.store.StoreBaseSyncTest"/>
</testsuite> <!-- Store Base Sync Tests -->
