<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="shushudelichendebijibendiannao.local" name="com.saas.qa.api.testcase.open.circle.StoreCircleSyncTest" tests="3" failures="2" timestamp="2025-03-04T13:41:42 CST" time="15.335" errors="0">
  <testcase name="testCircleSync_InvalidField" time="5.097" classname="com.saas.qa.api.testcase.open.circle.StoreCircleSyncTest">
    <failure type="java.lang.AssertionError" message="结果不符合预期 expected [未找到该门店渠道表数据] but found [delFlg不为null,circleDTO={&quot;channelId&quot;:999,&quot;circleId&quot;:&quot;test_circle_001&quot;,&quot;deliveryServiceType&quot;:9,&quot;enabled&quot;:1,&quot;fee&quot;:5000,&quot;feeType&quot;:1,&quot;name&quot;:&quot;测试服务圈&quot;,&quot;saasCircleId&quot;:1001,&quot;saasStoreId&quot;:7315,&quot;storeId&quot;:&quot;test57_hello&quot;}]">
        <![CDATA[java.lang.AssertionError: 结果不符合预期 expected [未找到该门店渠道表数据] but found [delFlg不为null,circleDTO={"channelId":999,"circleId":"test_circle_001","deliveryServiceType":9,"enabled":1,"fee":5000,"feeType":1,"name":"测试服务圈","saasCircleId":1001,"saasStoreId":7315,"storeId":"test57_hello"}]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.saas.qa.api.testcase.open.circle.StoreCircleSyncTest.testCircleSync_InvalidField(StoreCircleSyncTest.java:90)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.saas.qa.api.utils.TestReportGenerator.runTests(TestReportGenerator.java:73)
at com.saas.qa.api.utils.TestReportGenerator.generateAndOpenReport(TestReportGenerator.java:53)
at com.saas.qa.api.utils.TestReportGenerator.main(TestReportGenerator.java:154)
]]>
    </failure>
  </testcase> <!-- testCircleSync_InvalidField -->
  <system-out/>
  <testcase name="testCircleSync_MissingRequired" time="5.091" classname="com.saas.qa.api.testcase.open.circle.StoreCircleSyncTest">
    <failure type="java.lang.AssertionError" message="结果不符合预期 expected [1] but found [open_store_001]">
        <![CDATA[java.lang.AssertionError: 结果不符合预期 expected [1] but found [open_store_001]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.saas.qa.api.testcase.open.circle.StoreCircleSyncTest.testCircleSync_MissingRequired(StoreCircleSyncTest.java:67)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.saas.qa.api.utils.TestReportGenerator.runTests(TestReportGenerator.java:73)
at com.saas.qa.api.utils.TestReportGenerator.generateAndOpenReport(TestReportGenerator.java:53)
at com.saas.qa.api.utils.TestReportGenerator.main(TestReportGenerator.java:154)
]]>
    </failure>
  </testcase> <!-- testCircleSync_MissingRequired -->
  <system-out/>
  <testcase name="testCircleSync_Success" time="5.147" classname="com.saas.qa.api.testcase.open.circle.StoreCircleSyncTest"/>
  <system-out/>
</testsuite> <!-- com.saas.qa.api.testcase.open.circle.StoreCircleSyncTest -->
