<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="shushudelichendebijibendiannao.local" name="com.saas.qa.api.testcase.open.store.StoreBaseSyncTest" tests="3" failures="2" timestamp="2025-03-04T13:41:47 CST" time="15.549" errors="0">
  <testcase name="testStoreBaseSync_InvalidField" time="5.085" classname="com.saas.qa.api.testcase.open.store.StoreBaseSyncTest">
    <failure type="java.lang.AssertionError" message="结果不符合预期 expected [渠道ID不存在] but found [delFlg不为null,storeInfoRequest={&quot;address&quot;:&quot;北京市朝阳区测试地址&quot;,&quot;channelId&quot;:999,&quot;longLat&quot;:{&quot;latitude&quot;:999.999999,&quot;longitude&quot;:999.999999},&quot;merchantId&quot;:57,&quot;posHub&quot;:9,&quot;saasStoreId&quot;:7315,&quot;selfServiceDistance&quot;:1,&quot;storeId&quot;:&quot;test57_hello&quot;,&quot;storeName&quot;:&quot;测试门店&quot;,&quot;storePosType&quot;:9,&quot;storeStatus&quot;:9,&quot;storeType&quot;:9}]">
      <![CDATA[java.lang.AssertionError: 结果不符合预期 expected [渠道ID不存在] but found [delFlg不为null,storeInfoRequest={"address":"北京市朝阳区测试地址","channelId":999,"longLat":{"latitude":999.999999,"longitude":999.999999},"merchantId":57,"posHub":9,"saasStoreId":7315,"selfServiceDistance":1,"storeId":"test57_hello","storeName":"测试门店","storePosType":9,"storeStatus":9,"storeType":9}]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.saas.qa.api.testcase.open.store.StoreBaseSyncTest.testStoreBaseSync_InvalidField(StoreBaseSyncTest.java:91)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.saas.qa.api.util.TestReportGenerator.runTests(TestReportGenerator.java:73)
at com.saas.qa.api.util.TestReportGenerator.generateAndOpenReport(TestReportGenerator.java:53)
at com.saas.qa.api.util.TestReportGenerator.main(TestReportGenerator.java:154)
]]>
    </failure>
  </testcase> <!-- testStoreBaseSync_InvalidField -->
  <system-out/>
  <testcase name="testStoreBaseSync_Success" time="5.368" classname="com.saas.qa.api.testcase.open.store.StoreBaseSyncTest"/>
  <system-out/>
  <testcase name="testStoreBaseSync_MissingRequired" time="5.096" classname="com.saas.qa.api.testcase.open.store.StoreBaseSyncTest">
    <failure type="java.lang.AssertionError" message="结果不符合预期 expected [门店名称不能为空] but found [delFlg不为null,storeInfoRequest={&quot;address&quot;:&quot;北京市朝阳区测试地址&quot;,&quot;channelId&quot;:2,&quot;longLat&quot;:{&quot;latitude&quot;:39.909946,&quot;longitude&quot;:116.397428},&quot;merchantId&quot;:57,&quot;posHub&quot;:0,&quot;saasStoreId&quot;:7315,&quot;selfServiceDistance&quot;:1,&quot;storeId&quot;:&quot;test57_hello&quot;,&quot;storePosType&quot;:1,&quot;storeStatus&quot;:1,&quot;storeType&quot;:0}]">
      <![CDATA[java.lang.AssertionError: 结果不符合预期 expected [门店名称不能为空] but found [delFlg不为null,storeInfoRequest={"address":"北京市朝阳区测试地址","channelId":2,"longLat":{"latitude":39.909946,"longitude":116.397428},"merchantId":57,"posHub":0,"saasStoreId":7315,"selfServiceDistance":1,"storeId":"test57_hello","storePosType":1,"storeStatus":1,"storeType":0}]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.saas.qa.api.testcase.open.store.StoreBaseSyncTest.testStoreBaseSync_MissingRequired(StoreBaseSyncTest.java:68)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.saas.qa.api.util.TestReportGenerator.runTests(TestReportGenerator.java:73)
at com.saas.qa.api.util.TestReportGenerator.generateAndOpenReport(TestReportGenerator.java:53)
at com.saas.qa.api.util.TestReportGenerator.main(TestReportGenerator.java:154)
]]>
    </failure>
  </testcase> <!-- testStoreBaseSync_MissingRequired -->
  <system-out/>
</testsuite> <!-- com.saas.qa.api.testcase.open.store.StoreBaseSyncTest -->
